const translations = {
    de: {
        "hero-title": "DVB-C+ & Holo+ OS: Gesamtspezifikation",
        "hero-desc": "Das Betriebssystem Holo+ bildet die native Schnittstellenplattform für das hybride Kabelsystem DVB-C+. Es regelt die hardwarebeschleunigte Dekodierung hochbitratiger Medienströme, die Ausführung von sendereigenen interaktiven Overlays (OmniView) sowie globalen Systemapplikationen (Apps).",
        "contrib-title": "Werde Teil der TV-Revolution!",
        "contrib-desc": "DVB-C+ und Holo+ OS sind Open-Source-Projekte, die von der Community leben. Egal ob du Kernel-Entwickler bist, dich mit Tuner-Architekturen auskennst oder App-Blueprints schreibst.",
        "contrib-btn": "Jetzt auf GitHub mitwirken",
        "charta-title": "1. Die Holo+ Werbe- & Performance-Charta",
        "charta-tv-allow": "Erlaubt (Klassische TV-Werbung):",
        "charta-tv-allow-desc": "Traditionelle Werbeblöcke im linearen Videostream der Sender sind vollumfänglich erlaubt.",
        "charta-app-allow": "Erlaubt (Moderate App- & OmniView-Werbung):",
        "charta-app-allow-desc": "Innerhalb globaler Apps (.hap) und dem OmniView-Interface (.oip) is Werbung in moderaten Mengen gestattet.",
        "charta-forbidden": "Strengstens verboten (Tracker & Werbe-Spam):",
        "charta-forbidden-desc": "Jegliche Form von unsichtbaren Trackern zur Datensammlung ist verboten.",
        "charta-no-ai": "Kein AI-Slop:",
        "charta-no-ai-desc": "Holo+ verzichtet vollständig auf künstlich aufgeblasene Marketing-Features.",
        "hw-title": "2. Hardware- & Tuner-Architektur & Retro-Upscaler",
        "hw-single": "Single-Tuner-Geräte:",
        "hw-single-desc": "Exklusiv für den DVB-C+ Standard.",
        "hw-dual": "Dual-Tuner-Geräte (Retail-Standard):",
        "hw-dual-desc": "Bieten volle Abwärtskompatibilität.",
        "hw-scaler": "Der Native Retro-Upscaler:",
        "hw-scaler-desc": "Für analoge Signale und digitale Streams mit einer Auflösung von 480p und weniger.",
        "hw-scaler-func": "Funktionsweise:",
        "hw-scaler-func-desc": "Nutzt einen präzisen Integer-Scaling-Algorithmus.",
        "hw-scaler-req": "Hardware-Voraussetzung:",
        "hw-scaler-req-desc": "Dieses Feature erfordert ausreichende GPU-Power.",
        "sec-title": "3. In-Stream Keystore-Update & Offline-Sicherheit",
        "sec-carousel": "Globales Keystore-Karussell:",
        "sec-carousel-desc": "Jeder DVB-C+ Transponder strahlt kontinuierlich den Master-Keystore aus.",
        "sec-checksum": "Mathematische Prüfziffer (Fallback):",
        "sec-checksum-desc": "Offizielle Zertifikate enthalten eine integrierte Prüfziffer.",
        "sec-window": "30-Tage-Vertrauensfenster:",
        "sec-window-desc": "Schlägt die Formel fehl, läuft die Software für 30 Tage als Kulanz.",
        "cert-title": "4. Sicherheits- & Zertifikats-Struktur",
        "cert-desc": "Zertifikate sind UTF-8-kodierte Textdateien, die das OS in numerische Werte auflöst:",
        "cert-hoc": "256 Zeichen. Für sendergebundene .oip-Interfaces.",
        "cert-hac": "256 Zeichen. Für globale Apps (.hap).",
        "cert-hsc": "512 Zeichen. Zwingend erforderlich für System-Services.",
        "cert-code-title": "Syntax-Aufbau einer Zertifikatsdatei",
        
        /* Blueprint Syntax Strings */
        "bp-comment-1": "#Holo+ Application/OmniView/System Zertifikat",
        "bp-comment-2": "#Verteilt durch NeoAudio am 1. Juni 2026 (gültig für 4 Jahre)",
        "bp-comment-3": "#Zertifikatsschlüssel:",
        "bp-key-1": "[256/512 Zeichen Schlüssel]",
        "bp-comment-4": "#Prüfsumme:",
        "bp-key-2": "[32 Zeichen Zahl, mathematische Formel]",
        
        "cert-marker": "Parser-Mechanik:",
        "cert-marker-desc": "Das invertierte Ausrufezeichen ¡ dient dem OS-Kernel als absoluter Startpunkt.",
        "cert-dev-title": "Der Development-Modus (Unsigniert)",
        "cert-dev-desc": "Software ohne gültiges Zertifikat läuft in einer Sandbox ohne Systemzugriff.",
        "oip-title": "5. Das OmniView-Interface (.oip)",
        "oip-rest-title": "Sicherheits-Restriktion:",
        "oip-rest-desc": "Das OmniView-Interface ist ein reines, flüchtiges Anzeige- und Steuerungselement.",
        "oip-schema": "Interface-Namensschema:",
        "oip-blueprint": "Blueprint: Struktur eines OmniView-Interfaces (.oip)",
        
        "bp-oip-manifest": "<- Das Interface-Manifest",
        "bp-oip-cert": "<- Das verifizierte Zertifikat",
        "bp-oip-start": "<- Der definierte Startpunkt",
        "bp-oip-deps": "<- Ordner für Code-Abhängigkeiten",
        "bp-oip-assets": "<- Lokale Grafiken und Assets",

        "hap-title": "6. Globale Apps & Kernel-API Struktur (.hap)",
        "hap-schema": "Paket-Namensschema:",
        "hap-desc": "Macht Unterscheidungen zwischen drei strukturellen Abhängigkeitstypen:",
        "api-type1": "Shared System Frameworks: Globale Core-Frameworks (react, enact).",
        "api-type2": "System Core APIs (holo-app-core): Restriktive System-Schnittstellen.",
        "api-type3": "Selbstgeladene Dependencies: Eigene Libraries im Paket-Pfad.",
        "hap-blueprint": "Blueprint: Struktur einer Holo+ App (.hap)",
        
        "bp-hap-manifest": "<- Das App-Manifest",
        "bp-hap-cert": "<- Das App-Zertifikat",
        "bp-hap-syscert": "<- Das System-Zertifikat",
        "bp-hap-start": "<- Der App-Startpunkt",
        "bp-hap-deps": "<- Ordner für Abhängigkeiten",
        "bp-hap-depfile": "<- Entwickler-Dependency",
        "bp-hap-depapps": "<- Erforderliche Dependency-Apps",
        "bp-hap-assets": "<- Lokale Medien assets",

        "mal-title": "8. Der Malware-Review- & System-Service-Installationsprozess",
        "mal-step1": "Paket-Isolierung:",
        "mal-step1-desc": "Das OS scannt die Konfiguration und friert unautorisierte Prozesse ein.",
        "mal-step2": "Das Malware-Review-Popup:",
        "mal-step2-desc": "Ein unumgehbares Sicherheits-Popup öffnet sich zur statischen Code-Analyse.",
        "mal-step3": "Explizite Nutzerbestätigung:",
        "mal-step3-desc": "Die Installation erfordert die manuelle Autorisierung durch den Operator.",
        "feat-title": "9. Next-Gen Features von DVB-C+",
        "feat-zap": "Instant-Zap (Pre-Caching):",
        "feat-zap-desc": "Schnelles Umschalten unter 0,1 Sekunden durch FBC-Tuner.",
        "feat-audio": "Clean-Dialogue-Audio-Mischer:",
        "feat-audio-desc": "Erhöhung der Sprachverständlichkeit über Hardware-Kanäle.",
        "run-title": "10. System-Laufzeitverhalten & Hardware",
        "run-proc": "Der Umschalt-Prozess:",
        "run-step1": "Demuxing & Update: Der Tuner splittet das Signal offline auf.",
        "run-step2": "OmniView-Boot: Das Paket wird über die Keystore-Instanz validiert.",
        "run-step3": "Internet-Sperre: Fehlende Netzwerke erzwingen den kontrollierten Verbindungsabbruch.",
        "run-step4": "Rendering: Hardwarebeschleunigtes Rendering bei stabilen 60 Bildern pro Sekunde.",
        "run-hw-title": "Off-the-Shelf Hardware-Empfehlung",
        "run-hw-desc": "Vu+ Ultimo 4K: Die Premium-Wahl wegen der massiven FBC-Tuner-Architektur."
    },
    en: {
        "hero-title": "DVB-C+ & Holo+ OS: Full Specification",
        "hero-desc": "The Holo+ operating system forms the native interface platform for the hybrid cable system DVB-C+. It governs the hardware-accelerated decoding of high-bitrate media streams, the execution of station-owned interactive overlays (OmniView), and global system applications (Apps).",
        "contrib-title": "Join the TV Revolution!",
        "contrib-desc": "DVB-C+ and Holo+ OS are open-source projects that thrive on community contributions. Whether you are a kernel developer, familiar with tuner architecture, or writing app blueprints.",
        "contrib-btn": "Contribute on GitHub Now",
        "charta-title": "1. The Holo+ Advertising & Performance Charta",
        "charta-tv-allow": "Allowed (Classic TV Ads):",
        "charta-tv-allow-desc": "Traditional ad breaks within the linear video stream of the stations are fully allowed.",
        "charta-app-allow": "Allowed (Moderate App & OmniView Ads):",
        "charta-app-allow-desc": "Within global apps (.hap) and the OmniView interface (.oip), moderate advertising is permitted to fund developers.",
        "charta-forbidden": "Strictly Prohibited (Trackers & Spam):",
        "charta-forbidden-desc": "Any type of invisible background trackers is prohibited at protocol level.",
        "charta-no-ai": "No AI Slop:",
        "charta-no-ai-desc": "Holo+ completely rejects bloated marketing concepts.",
        "hw-title": "2. Hardware & Tuner Architecture & Retro Upscaler",
        "hw-single": "Single-Tuner Devices:",
        "hw-single-desc": "Exclusively engineered for the DVB-C+ platform.",
        "hw-dual": "Dual-Tuner Devices (Retail Standard):",
        "hw-dual-desc": "Features full legacy compatibility.",
        "hw-scaler": "The Native Retro Upscaler:",
        "hw-scaler-desc": "For analog inputs or legacy digital video feeds at or below 480p resolution.",
        "hw-scaler-func": "Operation:",
        "hw-scaler-func-desc": "Deploys a sharp hardware integer-scaling filter.",
        "hw-scaler-req": "Hardware Dependency:",
        "hw-scaler-req-desc": "This system feature requires verified GPU processing capabilities.",
        "sec-title": "3. In-Stream Keystore Carousel & Offline Integrity",
        "sec-carousel": "Transponder Key Carousel:",
        "sec-carousel-desc": "Every DVB-C+ transponder actively pushes the latest master keystore cycle.",
        "sec-checksum": "Mathematical Validation Fallback:",
        "sec-checksum-desc": "Legitimate code packages contain specialized checksum tags.",
        "sec-window": "30-Day Grace Period:",
        "sec-window-desc": "If local mathematical proofing fails, an interface is granted 30 days of limited runtime.",
        "cert-title": "4. Security & Certificate Layers",
        "cert-desc": "Certificates are simple UTF-8 text files resolved locally into raw cryptographic states:",
        "cert-hoc": "256 chars. For station-locked .oip interactive overlays.",
        "cert-hac": "256 chars. For global dashboard applications (.hap).",
        "cert-hsc": "512 chars. Enforced requirement for low-level system services.",
        "cert-code-title": "Syntax Architecture of a Certificate File",
        
        /* Blueprint Syntax Strings EN */
        "bp-comment-1": "#Holo+ Application/OmniView/System Certificate",
        "bp-comment-2": "#Distributed by NeoAudio on the 1st of June 2026 (valid for 4 years)",
        "bp-comment-3": "#Certificate Key:",
        "bp-key-1": "[256/512 character key]",
        "bp-comment-4": "#Checksum:",
        "bp-key-2": "[32 character numeric, mathematical formula]",

        "cert-marker": "Parser Logic:",
        "cert-marker-desc": "The inverted exclamation point ¡ marks the exact starting point.",
        "cert-dev-title": "Development Sandbox (Unsigned Code)",
        "cert-dev-desc": "Any package missing a valid code signature runs in an isolated sandbox.",
        "oip-title": "5. The OmniView Interface Architecture (.oip)",
        "oip-rest-title": "System Restrictions:",
        "oip-rest-desc": "The OmniView layout layer is an ephemeral display element.",
        "oip-schema": "Container Naming Logic:",
        "oip-blueprint": "Blueprint: OmniView Bundle Tree (.oip)",
        
        "bp-oip-manifest": "<- Interface manifest descriptor",
        "bp-oip-cert": "<- NeoAudio approved signature validation file",
        "bp-oip-start": "<- Main interface layout hook for the overlay engine",
        "bp-oip-deps": "<- Library dependencies and style layers",
        "bp-oip-assets": "<- Channel iconography, assets and fonts",

        "hap-title": "6. Global Application Layer & Kernel API (.hap)",
        "hap-schema": "Bundle Naming Logic:",
        "hap-desc": "To ensure maximum protection, Holo+ identifies three core dependency tiers:",
        "api-type1": "Shared System Frameworks: Standardized web frameworks pre-baked into the OS kernel.",
        "api-type2": "System Core APIs (holo-app-core): Locked system hardware access layers.",
        "api-type3": "Custom Local Dependencies: Unique developer extensions bundled within the container.",
        "hap-blueprint": "Blueprint: Holo+ Standalone Application Bundle (.hap)",
        
        "bp-hap-manifest": "<- Application manifest descriptor",
        "bp-hap-cert": "<- 256-char core application signature",
        "bp-hap-syscert": "<- Low-level 512-char authentication signature",
        "bp-hap-start": "<- Main entry node rendered within the sandboxed container",
        "bp-hap-deps": "<- Reserved for local script assets",
        "bp-hap-depfile": "<- Embedded script instance asset link",
        "bp-hap-depapps": "<- Required helper binaries or background components",
        "bp-hap-assets": "<- Static resources and localized file buffers",

        "mal-title": "8. Security Audits & Low-Level Privilege Authorization",
        "mal-step1": "Container Isolation:",
        "mal-step1-desc": "The OS runs a mandatory check on application parameters to suspend rogue tasks.",
        "mal-step2": "The Malware Review Dashboard:",
        "mal-step2-desc": "An unbypassable system alert module triggers static structure checks.",
        "mal-step3": "Explicit Administrative Consent:",
        "mal-step3-desc": "Installation remains frozen until human operator authorization is supplied.",
        "feat-title": "9. Next-Gen Specs within DVB-C+",
        "feat-zap": "Instant-Zap Channel Caching:",
        "feat-zap-desc": "Zapping operations execute under 0.1 seconds via FBC tuner matrix pipelines.",
        "feat-audio": "Isolated Vocal Feed Matrix:",
        "feat-audio-desc": "Broadcasters can process distinct dialog tracks natively on separate feeds.",
        "run-title": "10. Runtime Engine Flow & Targeted Target Architecture",
        "run-proc": "The Channel Zap Sequence:",
        "run-step1": "Demuxing & Update: The tuner processes parameters while caching files offline.",
        "run-step2": "OmniView Boot: The context is verified via keystore layers.",
        "run-step3": "Network Verification: Missing target connections trigger immediate structural termination.",
        "run-step4": "Overlay Rendering: Stable UI frame compositing locked at a 60 FPS output matrix.",
        "run-hw-title": "Off-the-Shelf Reference Implementations",
        "run-hw-desc": "Vu+ Ultimo 4K: The base baseline choice featuring proper high tier tuner components."
    },
    nl: {
        "hero-title": "DVB-C+ & Holo+ OS: Volledige Specificatie",
        "hero-desc": "Het Holo+ besturingssysteem vormt het natieve interfacesplatform voor het hybride kabelsysteem DVB-C+.",
        "contrib-title": "Bouw mee aan de tv-revolutie!",
        "contrib-desc": "DVB-C+ und Holo+ OS zijn open-source projecten. Of je nu een kernel-ontwikkelaar bent of app-blueprints schrijft.",
        "contrib-btn": "Werk nu mee op GitHub",
        "charta-title": "1. Het Holo+ Reclame- & Prestatiehandvest",
        "charta-tv-allow": "Toegestaan (Klassieke TV-reclame):",
        "charta-tv-allow-desc": "Traditionele reclameblokken in de lineaire videostream van de zenders zijn volledig toegestaan.",
        "charta-app-allow": "Toegestaan (Matige App- & OmniView-reclame):",
        "charta-app-allow-desc": "Binnen globale apps (.hap) en de OmniView-interface (.oip) is reclame in matige hoeveelheden toegestaan.",
        "charta-forbidden": "Strikt verboden (Trackers & Advertentiespam):",
        "charta-forbidden-desc": "Elke vorm van onzichtbare trackers voor gegevensverzameling is verboden.",
        "charta-no-ai": "Geen AI-Slop:",
        "charta-no-ai-desc": "Holo+ ziet volledig af van opgeklopte marketingfuncties.",
        "hw-title": "2. Hardware- & Tunerarchitectuur & Retro-Upscaler",
        "hw-single": "Single-Tuner-apparaten:",
        "hw-single-desc": "Exclusief voor de DVB-C+ standaard.",
        "hw-dual": "Dual-Tuner-apparaten (Winkelstandaard):",
        "hw-dual-desc": "Bieden volledige achterwaartse compatibiliteit.",
        "hw-scaler": "De Natieve Retro-Upscaler:",
        "hw-scaler-desc": "Voor analoge signalen und digitale streams met een resolutie van 480p en minder.",
        "hw-scaler-func": "Werking:",
        "hw-scaler-func-desc": "Maakt gebruik van een nauwkeurig integer-scaling-algoritme.",
        "hw-scaler-req": "Hardwarevereiste:",
        "hw-scaler-req-desc": "Deze functie vereist voldoende GPU-kracht.",
        "sec-title": "3. In-Stream Keystore-Update & Offline Beveiliging",
        "sec-carousel": "Globaal Keystore-Carrousel:",
        "sec-carousel-desc": "Elke DVB-C+ transponder zendt continu de nieuwste master-keystore uit.",
        "sec-checksum": "Wiskundig controlegetal (Fallback):",
        "sec-checksum-desc": "Officiële certificaten bevatten een geïntegreerd controlegetal.",
        "sec-window": "30-Dagen Vertrouwensvenster:",
        "sec-window-desc": "Als de formule faalt, werkt de software 30 dagen als coulanceperiode.",
        "cert-title": "4. Beveiligings- & Certificaatstructuur",
        "cert-desc": "Certificaten zijn UTF-8 gecodeerde tekstbestanden die het OS omzet in numerieke waarden:",
        "cert-hoc": "256 tekens. Voor zendergebonden .oip-interfaces.",
        "cert-hac": "256 tekens. Voor globale apps (.hap).",
        "cert-hsc": "512 tekens. Verplicht voor systeemdiensten met diepe rechten.",
        "cert-code-title": "Syntaxstructuur van een Certificaatbestand",
        
        /* Blueprint Syntax Strings NL */
        "bp-comment-1": "#Holo+ Applicatie/OmniView/Systeem Certificaat",
        "bp-comment-2": "#Gedistribueerd door NeoAudio op 1 juni 2026 (4 jaar geldig)",
        "bp-comment-3": "#Certificaatsleutel:",
        "bp-key-1": "[256/512 tekens sleutel]",
        "bp-comment-4": "#Controlegetal:",
        "bp-key-2": "[32 tekens nummer, wiskundige formule]",

        "cert-marker": "Parser-mechanisme:",
        "cert-marker-desc": "Het omgekeerde uitroepteken ¡ dient als het absolute startpunt.",
        "cert-dev-title": "De Ontwikkelmodus (Niet ondertekend)",
        "cert-dev-desc": "Software zonder geldig certificaat draait in een sandbox zonder systeemtoegang.",
        "oip-title": "5. De OmniView-Interface (.oip)",
        "oip-rest-title": "Beveiligingsrestrictie:",
        "oip-rest-desc": "De OmniView-interface is een puur vluchtig weergave- en bedieningselement.",
        "oip-schema": "Interface-naamschema:",
        "oip-blueprint": "Blueprint: Structuur van een OmniView-interface (.oip)",
        
        "bp-oip-manifest": "<- Het Interface-Manifest",
        "bp-oip-cert": "<- Het geverifieerde certificaat",
        "bp-oip-start": "<- Het gedefinieerde startpunt voor de TV-overlay",
        "bp-oip-deps": "<- Map voor script-gebaseerde afhankelijkheden",
        "bp-oip-assets": "<- Lokale afbeeldingen, zenderlogo's en assets",

        "hap-title": "6. Globale Apps & Kernel-API Structuur (.hap)",
        "hap-schema": "Pakket-naamschema:",
        "hap-desc": "Om systeembeveiliging te combineren, maakt Holo+ strikt onderscheid tussen drie typen afhankelijkheden:",
        "api-type1": "Shared System Frameworks: Globale webframeworks geïntegreerd in het OS.",
        "api-type2": "System Core APIs (holo-app-core): Beperkende systeeminterfaces voor hardwarebronnen.",
        "api-type3": "Custom Local Dependencies: Lokale ontwikkelaarsbibliotheken meegeleverd onder het deps/ pad.",
        "hap-blueprint": "Blueprint: Structuur van een Holo+ App (.hap)",
        
        "bp-hap-manifest": "<- Het App-Manifest",
        "bp-hap-cert": "<- Het 256-tekens App-Certificaat",
        "bp-hap-syscert": "<- Het 512-tekens Systeem-Certificaat",
        "bp-hap-start": "<- Het gedefinieerde startpunt in de Chromium-core",
        "bp-hap-deps": "<- Map voor exclusieve code-afhankelijkheden",
        "bp-hap-depfile": "<- Voorbeeld van een zelfgeladen dependency",
        "bp-hap-depapps": "<- Map voor verplichte dependency-apps",
        "bp-hap-assets": "<- Lokale afbeeldingen en audio-assets",

        "mal-title": "8. Het Malware-Review- & Systeemservice-installatieproces",
        "mal-step1": "Pakketisolatie:",
        "mal-step1-desc": "Het OS scannt configuraties en bevriest onbevoegde acties direct.",
        "mal-step2": "De Malware-Review-Popup:",
        "mal-step2-desc": "Er opent een automatische systeembrede beveiligingspopup voor codeanalyse.",
        "mal-step3": "Explicit Gebruikersbevestiging:",
        "mal-step3-desc": "De installatie vereist actieve handmatige goedkeuring door de operator.",
        "feat-title": "9. Next-Gen Functies van DVB-C+",
        "feat-zap": "Instant-Zap (Pre-Caching):",
        "feat-zap-desc": "Zappen duurt minder dan 0,1 seconden via FBC-tuners.",
        "feat-audio": "Clean-Dialogue-Audiomixer:",
        "feat-audio-desc": "Zenders sturen een aparte audiolaag mee voor pure spraaksturing via hardware.",
        "run-title": "10. Systeemlooptijdgedrag & Hardware",
        "run-proc": "Het Zapproces:",
        "run-step1": "Demuxing & Update: De tuner demuxt signalen en verwerkt keystores op de achtergrond.",
        "run-step2": "OmniView-Boot: Validatie van pakketten via lokale sleutelstructuren.",
        "run-step3": "Internetblokkade: Het ontbreken van verbindingen breekt processen direct af.",
        "run-step4": "Rendering: Hardware-versnelde overlay weergave stabiel op 60 FPS.",
        "run-hw-title": "Off-the-Shelf Hardware-aanbeveling",
        "run-hw-desc": "Vu+ Ultimo 4K: De premium hardware keuze voorzien van geavanceerde tuners."
    }
};

document.getElementById('langSwitch').addEventListener('change', (e) => {
    switchLanguage(e.target.value);
});

function switchLanguage(lang) {
    document.documentElement.lang = lang;
    const elements = document.querySelectorAll('[data-i18n]');
    
    elements.forEach(elem => {
        const key = elem.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            const iconSpan = elem.querySelector('.material-symbols-outlined');
            if (iconSpan) {
                const textNode = Array.from(elem.childNodes).find(node => node.nodeType === Node.TEXT_NODE);
                if (textNode) {
                    textNode.textContent = " " + translations[lang][key];
                } else {
                    elem.innerHTML = iconSpan.outerHTML + " " + translations[lang][key];
                }
            } else {
                elem.textContent = translations[lang][key];
            }
        }
    });
}
