const translations = {
    de: {
        "hero-title": "DVB-C+ & Holo+ OS: Gesamtspezifikation",
        "hero-desc": "Das Betriebssystem Holo+ bildet die native Schnittstellenplattform für das hybride Kabelsystem DVB-C+. Es regelt die hardwarebeschleunigte Dekodierung hochbitratiger Medienströme, die Ausführung von sendereigenen interaktiven Overlays (OmniView) sowie globalen Systemapplikationen (Apps). Das System trennt zwischen isolierten Broadcast-Erweiterungen und tief integrierten Systemdiensten über ein proprietäres, mehrstufiges Sicherheits- und Zertifikatsmodell.",
        "contrib-title": "Werde Teil der TV-Revolution! (Mitarbeit)",
        "contrib-desc": "DVB-C+ und Holo+ OS sind offene Spezifikationen, die von Beiträgen aus der Community leben. Egal ob du Kernel-Entwickler bist, dich mit Tuner-Demuxing auskennst, App-Blueprints schreibst oder die Dokumentation verbessern willst – jede Hilfe bringt uns dem trackerfreien, modernen Kabelfernsehen näher.",
        "contrib-btn": "Jetzt auf GitHub mitwirken",
        "charta-title": "1. Die Holo+ Werbe- & Performance-Charta",
        "charta-tv-allow": "Erlaubt (Klassische TV-Werbung):",
        "charta-tv-allow-desc": "Traditionelle Werbeblöcke im linearen Videostream der Sender sind vollumfänglich erlaubt. Der Receiver greift nicht in das gesendete Bild- und Tonmaterial ein.",
        "charta-app-allow": "Erlaubt (Moderate App- & OmniView-Werbung):",
        "charta-app-allow-desc": "Innerhalb globaler Apps (.hap) und dem OmniView-Interface (.oip) ist Werbung (z. B. Banner, Empfehlungen, In-Content-Promotions) in moderaten Mengen gestattet, um die Entwickler und Sender zu finanzieren. Das visuelle Design darf den Nutzer jedoch nicht in der Kern-Bedienung blockieren oder Menüstrukturen unbrauchbar machen.",
        "charta-forbidden": "Strengstens verboten (Tracker & Werbe-Spam):",
        "charta-forbidden-desc": "Jegliche Form von unsichtbaren Trackern zur Datensammlung, Telemetrie-Schnüfflern, User-Behavior-Analyse oder aufdringlichem Werbe-Spam (z. B. unschließbare Pop-ups) ist auf Protokollebene verboten. Verstößt ein Entwickler oder Sender gegen diese Charta, wird das Zertifikat (.hoc / .hac) über die hardwarebasierte Revocation-List dauerhaft entzogen.",
        "charta-no-ai": "Kein AI-Slop:",
        "charta-no-ai-desc": "Holo+ verzichtet vollständig auf künstlich aufgeblasene Marketing-Features („AI-Optimierung“, „Smart-Predictive-Zapping“ etc.). Alle Bild- und Tonprozesse basieren auf mathematisch präzisen, deterministischen Algorithmen und direkter Hardware-Power, um maximale Stabilität und minimale System-Latenzzeiten zu garantieren.",
        "hw-title": "2. Hardware- & Tuner-Architektur & Retro-Upscaler",
        "hw-single": "Single-Tuner-Geräte:",
        "hw-single-desc": "Exklusiv für den DVB-C+ Standard (4K/8K via AV1/HEVC, Dolby Atmos/FLAC, OmniView).",
        "hw-dual": "Dual-Tuner-Geräte (Retail-Standard):",
        "hw-dual-desc": "Bieten volle Abwärtskompatibilität für klassisches DVB-C (über Tuner 2) und analoge RF-Signale (VHF/UHF).",
        "hw-scaler": "Der Native Retro-Upscaler:",
        "hw-scaler-desc": "Für analoge Signale und digitale Streams mit einer Auflösung von 480p und weniger (z. B. VHS-Videorekorder, Röhren-Konsolen) besitzt Holo+ einen dedizierten, hardwarebeschleunigten Upscaler.",
        "hw-scaler-func": "Funktionsweise:",
        "hw-scaler-func-desc": "Nutzt einen präzisen Integer-Scaling-Algorithmus (Pixel-Perfect-Modus) kombiniert mit einer optionalen, zuschaltbaren Scanline-Simulation, um Unschärfe-Artefakte moderner Panels zu eliminieren.",
        "hw-scaler-req": "Hardware-Voraussetzung:",
        "hw-scaler-req-desc": "Dieses Feature wird nur auf Receivern mit ausreichender GPU-Rechenleistung freigeschaltet.",
        "sec-title": "3. In-Stream Keystore-Update & Offline-Sicherheit",
        "sec-carousel": "Globales Keystore-Karussell:",
        "sec-carousel-desc": "Jeder DVB-C+ Transponder strahlt auf einer geschützten System-PID kontinuierlich den aktuellen, von NeoAudio (Kontakt: neoaudio@murena.io) signierten Master-Keystore aus. Der Receiver aktualisiert seine Sicherheitsdatenbank vollautomatisch und zu 100 % offline über das physische Kabelnetz.",
        "sec-checksum": "Mathematische Prüfziffer (Fallback):",
        "sec-checksum-desc": "Offizielle Zertifikate enthalten eine integrierte Prüfziffer. Die mathematische Formel im OS Holo+ kann diese bei echten Zertifikaten immer erfolgreich auflösen, wodurch das Interface sofort als verifiziert gilt.",
        "sec-window": "30-Tage-Vertrauensfenster:",
        "sec-window-desc": "Schlägt die Formel fehl und das Zertifikat ist unbekannt, läuft die Software für 30 Tage als Kulanz. Der Nutzer wird über diskrete System-Pop-ups gebeten, das Gerät kurzzeitig online zu synchronisieren. Nach 30 Tagen ohne Abgleich erfolgt die Herabstufung in den eingeschränkten Development-Modus.",
        "cert-title": "4. Sicherheits- & Zertifikats-Struktur",
        "cert-desc": "Zertifikate sind UTF-8-kodierte Textdateien, die das OS in numerische Werte auflöst:",
        "cert-hoc": "256 Zeichen. Für sendergebundene .oip-Interfaces.",
        "cert-hac": "256 Zeichen. Für globale Apps (.hap).",
        "cert-hsc": "512 Zeichen. Zwingend erforderlich für System-Services mit tiefen Rechten.",
        "cert-dev-title": "Der Development-Modus (Unsigniert)",
        "cert-dev-desc": "Software ohne gültiges Zertifikat läuft in einer Sandbox ohne Systemzugriff, zeigt vor dem Start eine Warnung und trägt ein permanentes, transparentes Branding-Badge („Development OmniView Interface“ bzw. „Development Holo+ App“).",
        "oip-title": "5. Das OmniView-Interface (.oip)",
        "oip-rest-title": "Sicherheits-Restriktion:",
        "oip-rest-desc": "Das OmniView-Interface ist ein reines, flüchtiges Anzeige- und Steuerungselement. Im Gegensatz zu globalen Apps ist es einem .oip-Paket auf Systemebene strengstens verboten, eigene Apps, Erweiterungen oder Systemdienste mitzuführen oder nachzuinstallieren. Es darf keinerlei dep-apps-Unterordner besitzen.",
        "oip-schema": "Interface-Namensschema:",
        "oip-blueprint": "Blueprint: Struktur eines OmniView-Interfaces (.oip)",
        "oip-json": "Spezifikation der infotainmentinfo.json",
        "hap-title": "6. Globale Apps & Kernel-API Struktur (.hap)",
        "hap-schema": "Paket-Namensschema:",
        "hap-desc": "Um Systemsicherheit und schlanke Pakete zu vereinen, unterscheidet Holo+ strikt zwischen drei Abhängigkeitstypen:",
        "api-type1": "Shared System Frameworks: Globale, im OS integrierte Web-Frameworks (react, enact, hls.js).",
        "api-type2": "System Core APIs (holo-app-core): Restriktive System-Schnittstellen. Ermöglicht Lese- und Schreibzugriff auf sensible Hardware-Ressourcen wie den Tuner-Status, Signalstärken oder den WLAN-Chipsatz.",
        "api-type3": "Selbstgeladene Dependencies (Custom Dependencies): Lokale Bibliotheken des Entwicklers, die im Paket mitgeliefert und über den relativen Pfad deps/ angesprochen werden.",
        "hap-blueprint": "Blueprint: Struktur einer Holo+ App (.hap)",
        "hap-json": "Spezifikation der appinfo.json",
        "mal-title": "8. Der Malware-Review- & System-Service-Installationsprozess",
        "mal-step1": "Paket-Isolierung:",
        "mal-step1-desc": "Das OS scannt die appinfo.json. Bei Erkennung von 'system' oder restriktiven Berechtigungsanforderungen innerhalb des holo-app-core wird der automatische Installationsprozess eingefroren.",
        "mal-step2": "Das Malware-Review-Popup:",
        "mal-step2-desc": "Ein unumgehbares, systemweites Sicherheits-Popup öffnet sich. Dieses Fenster führt eine automatisierte statische Code-Analyse des Dienstes durch und präsentiert eine klare Zusammenfassung, Erklärung und Risikobewertung.",
        "mal-step3": "Explizite Nutzerbestätigung:",
        "mal-step3-desc": "Die Installation wird erst fortgesetzt, wenn der Nutzer die Risiken aktiv bestätigt und die Installation des System-Services explizit autorisiert.",
        "feat-title": "9. Next-Gen Features von DVB-C+",
        "feat-zap": "Instant-Zap (Pre-Caching):",
        "feat-zap-desc": "Bei Geräten mit FBC-Tunern decodiert Holo+ die I-Frames der umliegenden Kanäle permanent im Hintergrund mit. Das Umschalten erfolgt in unter 0,1 Sekunden.",
        "feat-audio": "Clean-Dialogue-Audio-Mischer:",
        "feat-audio-desc": "Sender können eine separate PID für reine Dialoge mitschicken. Der Nutzer kann im Audiomenü die Stimmen stufenlos anheben – rein über Hardware-Mischung der Tonspuren.",
        "run-title": "10. System-Laufzeitverhalten & Hardware",
        "run-proc": "Der Umschalt-Prozess:",
        "run-step1": "Demuxing & Update: Der Tuner splittet das Signal. Im Hintergrund wird der Keystore über das Kabel aktualisiert.",
        "run-step2": "OmniView-Boot: Das .oip-Paket wird geladen, das .hoc-Zertifikat über die Formel oder den Keystore validiert.",
        "run-step3": "Internet-Sperre: Ist internet_required auf true und der Receiver offline, bricht der Ladevorgang ab und Holo+ gibt eine standardisierte Fehlermeldung aus.",
        "run-step4": "Rendering: Die hardwarebeschleunigte Web-Engine legt das Interface mit stabilen 60 FPS über das TV-Bild. Bei Kanälen von 480p und weniger schaltet sich der native Pixel-Perfect-Upscaler dazu.",
        "run-hw-title": "Off-the-Shelf Hardware-Empfehlung",
        "run-hw-desc": "Vu+ Ultimo 4K: Die Premium-Wahl wegen der massiven FBC-Tuner-Architektur und der Option, einen analogen RF-Zusatztuner für Retro-Geräte nachzurüsten. Liefert mehr als genug GPU-Power für den Upscaler, komplexe Chromium-Apps sowie für das Berechnen der Malware-Reviews bei System-Services."
    },
    en: {
        "hero-title": "DVB-C+ & Holo+ OS: Full Specification",
        "hero-desc": "The Holo+ operating system forms the native interface platform for the hybrid cable system DVB-C+. It governs the hardware-accelerated decoding of high-bitrate media streams, the execution of station-owned interactive overlays (OmniView), and global system applications (Apps). The system separates isolated broadcast extensions from deeply integrated system services via a proprietary, multi-tiered security and certificate model.",
        "contrib-title": "Join the TV Revolution! (Contribution)",
        "contrib-desc": "DVB-C+ and Holo+ OS are open specifications built on community collaboration. Whether you are a kernel developer, understand tuner demuxing, write application blueprints, or want to polish documentation – every contribution brings us closer to tracker-free, modern cable television.",
        "contrib-btn": "Contribute on GitHub Now",
        "charta-title": "1. The Holo+ Advertising & Performance Charta",
        "charta-tv-allow": "Allowed (Classic TV Advertising):",
        "charta-tv-allow-desc": "Traditional commercial breaks in the linear video stream of the stations are fully permitted. The receiver does not alter the transmitted picture and sound material.",
        "charta-app-allow": "Allowed (Moderate App & OmniView Ads):",
        "charta-app-allow-desc": "Within global apps (.hap) and the OmniView interface (.oip), advertising (e.g., banners, recommendations, in-content promotions) is permitted in moderate amounts to fund developers and broadcasters. The visual design must not block the user in core operations.",
        "charta-forbidden": "Strictly Prohibited (Trackers & Ad Spam):",
        "charta-forbidden-desc": "Any form of invisible trackers for data collection, telemetry sniffers, user behavior analysis, or intrusive ad spam is prohibited at the protocol level. Violation results in permanent revocation of the certificate (.hoc / .hac).",
        "charta-no-ai": "No AI Slop:",
        "charta-no-ai-desc": "Holo+ completely dispenses with overhyped marketing features. All image and sound processes are based on mathematically precise, deterministic algorithms and direct hardware power.",
        "hw-title": "2. Hardware & Tuner Architecture & Retro Upscaler",
        "hw-single": "Single-Tuner Devices:",
        "hw-single-desc": "Exclusive to the DVB-C+ standard (4K/8K via AV1/HEVC, Dolby Atmos/FLAC, OmniView).",
        "hw-dual": "Dual-Tuner Devices (Retail Standard):",
        "hw-dual-desc": "Provide full backward compatibility for classic DVB-C (via Tuner 2) and analog RF signals (VHF/UHF).",
        "hw-scaler": "The Native Retro Upscaler:",
        "hw-scaler-desc": "For analog signals and digital streams with a resolution of 480p and less (e.g., VHS video recorders, CRT consoles).",
        "hw-scaler-func": "Functionality:",
        "hw-scaler-func-desc": "Uses a precise integer scaling algorithm (pixel-perfect mode) combined with an optional, toggleable scanline simulation.",
        "hw-scaler-req": "Hardware Requirement:",
        "hw-scaler-req-desc": "This feature is only unlocked on receivers with sufficient GPU computing power.",
        "sec-title": "3. In-Stream Keystore Update & Offline Security",
        "sec-carousel": "Global Keystore Carousel:",
        "sec-carousel-desc": "Each DVB-C+ transponder continuously broadcasts the current master keystore signed by NeoAudio. The receiver updates its security database completely offline via the cable network.",
        "sec-checksum": "Mathematical Checksum (Fallback):",
        "sec-checksum-desc": "Official certificates contain an integrated checksum. The mathematical formula in Holo+ OS can always successfully resolve this for genuine certificates.",
        "sec-window": "30-Day Trust Window:",
        "sec-window-desc": "If the formula fails, the software runs for 30 days as a grace period before being downgraded to the restricted Development Mode.",
        "cert-title": "4. Security & Certificate Structure",
        "cert-desc": "Certificates are UTF-8 encoded text files that the OS resolves into numerical values:",
        "cert-hoc": "256 characters. For station-bound .oip interfaces.",
        "cert-hac": "256 characters. For global apps (.hap).",
        "cert-hsc": "512 characters. Mandatory for system services with deep privileges.",
        "cert-dev-title": "Development Mode (Unsigned)",
        "cert-dev-desc": "Software without a valid certificate runs in a sandbox without system access and carries a permanent, transparent branding badge.",
        "oip-title": "5. The OmniView Interface (.oip)",
        "oip-rest-title": "Security Restriction:",
        "oip-rest-desc": "The OmniView interface is a purely volatile display and control element. It is strictly forbidden to bundle or install its own apps or system services. It must not contain a dep-apps subfolder.",
        "oip-schema": "Interface Naming Scheme:",
        "oip-blueprint": "Blueprint: Structure of an OmniView Interface (.oip)",
        "oip-json": "Specification of infotainmentinfo.json",
        "hap-title": "6. Global Apps & Kernel API Structure (.hap)",
        "hap-schema": "Package Naming Scheme:",
        "hap-desc": "To unite system security and lean packages, Holo+ strictly differentiates between three dependency types:",
        "api-type1": "Shared System Frameworks: Global web frameworks integrated into the OS (react, enact, hls.js).",
        "api-type2": "System Core APIs (holo-app-core): Restrictive system interfaces. Enables read and write access to sensitive hardware resources like tuner status or Wi-Fi chipset.",
        "api-type3": "Custom Local Dependencies: Local developer libraries shipped inside the package under the deps/ path.",
        "hap-blueprint": "Blueprint: Structure of a Holo+ App (.hap)",
        "hap-json": "Specification of appinfo.json",
        "mal-title": "8. Malware Review & System Service Installation Process",
        "mal-step1": "Package Isolation:",
        "mal-step1-desc": "The OS scans appinfo.json. Upon detection of 'system' or restrictive core permission requests, the automated installation process is frozen.",
        "mal-step2": "The Malware Review Popup:",
        "mal-step2-desc": "An unbypassable system-wide security popup opens. This window performs an automated static code analysis and displays a summary, explanation, and risk rating.",
        "mal-step3": "Explicit User Confirmation:",
        "mal-step3-desc": "The installation only proceeds once the user actively confirms the risks and explicitly authorizes the system service.",
        "feat-title": "9. Next-Gen Features of DVB-C+",
        "feat-zap": "Instant-Zap (Pre-Caching):",
        "feat-zap-desc": "On devices with FBC tuners, Holo+ permanently decodes the I-frames of surrounding channels in the background. Zapping takes less than 0.1 seconds.",
        "feat-audio": "Clean-Dialogue Audio Mixer:",
        "feat-audio-desc": "Broadcasters can send a separate PID for clean dialogues. The user can continuously raise voices via pure hardware track mixing.",
        "run-title": "10. System Runtime Behavior & Hardware",
        "run-proc": "The Zapping Process:",
        "run-step1": "Demuxing & Update: The tuner splits the signal. Keystore update runs in the background via cable.",
        "run-step2": "OmniView Boot: The .oip package is loaded, and the .hoc certificate is validated via formula or keystore.",
        "run-step3": "Internet Block: If offline and internet_required is true, the process aborts with a standardized system message.",
        "run-step4": "Rendering: Hardware-accelerated overlay at stable 60 FPS. The native pixel-perfect upscaler activates for channels ≤ 480p.",
        "run-hw-title": "Off-the-Shelf Hardware Recommendation",
        "run-hw-desc": "Vu+ Ultimo 4K: The premium choice due to the massive FBC tuner architecture and the option to retrofit an analog RF tuner. Delivers more than enough GPU power for upscaling, complex Chromium apps, and real-time malware reviews."
    },
    nl: {
        "hero-title": "DVB-C+ & Holo+ OS: Volledige Specificatie",
        "hero-desc": "Het Holo+ besturingssysteem vormt het natieve interfacesplatform voor het hybride kabelsysteem DVB-C+. Het regelt de hardware-versnelde decodering van mediastromen met hoge bitrates, de uitvoering van zendereigen interactieve overlays (OmniView) en globale systeemapplicaties (Apps). Het systeem scheidt geïsoleerde broadcast-extensies van diep geïntegreerde systeemdiensten via een eigen, gelaagd beveiligings- en certificaatmodel.",
        "contrib-title": "Bouw mee aan de tv-revolutie! (Bijdragen)",
        "contrib-desc": "DVB-C+ en Holo+ OS zijn open specificaties die floreren dankzij bijdragen van de community. Of je nu een kernel-ontwikkelaar bent, verstand hebt van tuner-demuxing, app-blueprints schrijft of documentatie wilt oppoetsen – alle hulp brengt ons dichter bij tracker-vrije, moderne kabeltelevisie.",
        "contrib-btn": "Werk nu mee op GitHub",
        "charta-title": "1. Het Holo+ Reclame- & Prestatiehandvest",
        "charta-tv-allow": "Toegestaan (Klassieke TV-reclame):",
        "charta-tv-allow-desc": "Traditionele reclameblokken in de lineaire videostream van de zenders zijn volledig toegestaan. De ontvanger grijpt niet in op het uitgezonden beeld- en geluidsmateriaal.",
        "charta-app-allow": "Toegestaan (Matige App- & OmniView-reclame):",
        "charta-app-allow-desc": "Binnen globale apps (.hap) en de OmniView-interface (.oip) is reclame (bijv. banners, aanbevelingen) in matige hoeveelheden toegestaan om ontwikkelaers en zenders te financieren. Het visuele ontwerp mag de gebruiker niet blokkeren.",
        "charta-forbidden": "Strikt verboden (Trackers & Advertentiespam):",
        "charta-forbidden-desc": "Elke vorm van onzichtbare trackers voor gegevensverzameling, telemetriesnuffelaars of opdringerige advertentiespam is verboden op protocolniveau. Overtreding leidt tot permanente intrekking van het certificaat (.hoc / .hac).",
        "charta-no-ai": "Geen AI-Slop:",
        "charta-no-ai-desc": "Holo+ ziet volledig af van opgeklopte marketingfuncties. Alle beeld- en geluidsprocessen zijn gebaseerd op wiskundig nauwkeurige, deterministische algoritmen en directe hardwarekracht.",
        "hw-title": "2. Hardware- & Tunerarchitectuur & Retro-Upscaler",
        "hw-single": "Single-Tuner-apparaten:",
        "hw-single-desc": "Exclusief voor de DVB-C+ standaard (4K/8K via AV1/HEVC, Dolby Atmos/FLAC, OmniView).",
        "hw-dual": "Dual-Tuner-apparaten (Winkelstandaard):",
        "hw-dual-desc": "Bieden volledige achterwaartse compatibiliteit voor klassieke DVB-C (via Tuner 2) and analoge RF-signalen (VHF/UHF).",
        "hw-scaler": "De Natieve Retro-Upscaler:",
        "hw-scaler-desc": "Voor analoge signalen en digitale streams met een resolutie van 480p en minder (bijv. VHS-videorecorders, beeldbuisconsoles).",
        "hw-scaler-func": "Werking:",
        "hw-scaler-func-desc": "Maakt gebruik van een nauwkeurig integer-scaling-algoritme (pixel-perfect modus) gecombineerd met een optionele scanlijnsimulatie.",
        "hw-scaler-req": "Hardwarevereiste:",
        "hw-scaler-req-desc": "Deze functie wordt alleen ontgrendeld op ontvangers met voldoende GPU-rekenkracht.",
        "sec-title": "3. In-Stream Keystore-Update & Offline Beveiliging",
        "sec-carousel": "Globaal Keystore-Carrousel:",
        "sec-carousel-desc": "Elke DVB-C+ transponder zendt continu de nieuwste door NeoAudio ondertekende master-keystore uit. De ontvanger werkt zijn database volledig offline bij via het kabelnetwerk.",
        "sec-checksum": "Wiskundig controlegetal (Fallback):",
        "sec-checksum-desc": "Officiële certificaten bevatten een geïntegreerd controlegetal. De wiskundige formule in Holo+ OS kan dit bij echte certificaten altijd succesvol controleren.",
        "sec-window": "30-Dagen Vertrouwensvenster:",
        "sec-window-desc": "Als de formule faalt, werkt de software 30 dagen als coulanceperiode voordat deze wordt gedowngraded naar de beperkte Ontwikkelmodus.",
        "cert-title": "4. Beveiligings- & Certificaatstructuur",
        "cert-desc": "Certificaten zijn UTF-8 gecodeerde tekstbestanden die het OS omzet in numerieke waarden:",
        "cert-hoc": "256 tekens. Voor zendergebonden .oip-interfaces.",
        "cert-hac": "256 tekens. Voor globale apps (.hap).",
        "cert-hsc": "512 tekens. Verplicht voor systeemdiensten met diepe rechten.",
        "cert-dev-title": "De Ontwikkelmodus (Niet ondertekend)",
        "cert-dev-desc": "Software zonder geldig certificaat draait in een sandbox zonder systeemtoegang en is voorzien van een permanente, transparante branding-badge.",
        "oip-title": "5. De OmniView-Interface (.oip)",
        "oip-rest-title": "Beveiligingsrestrictie:",
        "oip-rest-desc": "De OmniView-interface is een puur vluchtig weergave- en bedieningselement. Het is ten strengste verboden om eigen apps of systeemdiensten mee te leveren. Het mag geen dep-apps-submap bevatten.",
        "oip-schema": "Interface-naamschema:",
        "oip-blueprint": "Blueprint: Structuur van een OmniView-interface (.oip)",
        "oip-json": "Specificatie van infotainmentinfo.json",
        "hap-title": "6. Globale Apps & Kernel-API Structuur (.hap)",
        "hap-schema": "Pakket-naamschema:",
        "hap-desc": "Om systeembeveiliging en slanke pakketten te combineren, maakt Holo+ strikt onderscheid tussen drie typen afhankelijkheden:",
        "api-type1": "Shared System Frameworks: Globale webframeworks geïntegreerd in het OS (react, enact, hls.js).",
        "api-type2": "System Core APIs (holo-app-core): Beperkende systeeminterfaces. Geeft lees- en schrijftoegang tot gevoelige hardwarebronnen zoals de tunerstatus of wifi-chipset.",
        "api-type3": "Custom Local Dependencies: Lokale ontwikkelaarsbibliotheken die in het pakket worden meegeleverd onder het deps/ pad.",
        "hap-blueprint": "Blueprint: Structuur van een Holo+ App (.hap)",
        "hap-json": "Specificatie van appinfo.json",
        "mal-title": "8. Het Malware-Review- & Systeemservice-installatieproces",
        "mal-step1": "Pakketisolatie:",
        "mal-step1-desc": "Het OS scan appinfo.json. Bij detectie van 'system' of beperkende core-rechtenaanvragen wordt het automatische installatieproces bevroren.",
        "mal-step2": "De Malware-Review-Popup:",
        "mal-step2-desc": "Er opent een onvermijdelijke systeembrede beveiligingspopup. Dit venster voert een automatische statische codeanalyse uit en toont een samenvatting, uitleg en risicobeoordeling.",
        "mal-step3": "Expliciete Gebruikersbevestiging:",
        "mal-step3-desc": "De installatie wordt pas voortgezet nadat de gebruiker de risico's actief bevestigt en de installatie van de systeemservice expliciet autoriseert.",
        "feat-title": "9. Next-Gen Functies van DVB-C+",
        "feat-zap": "Instant-Zap (Pre-Caching):",
        "feat-zap-desc": "Bij apparaten met FBC-tuners decodeert Holo+ de I-frames van omliggende kanalen continu op de achtergrond. Zappen duurt minder dan 0,1 seconden.",
        "feat-audio": "Clean-Dialogue-Audiomixer:",
        "feat-audio-desc": "Zenders kunnen een aparte PID voor pure dialogen meesturen. De gebruiker kan stemmen traploos versterken via pure hardwarematige mixen van de geluidssporen.",
        "run-title": "10. Systeemlooptijdgedrag & Hardware",
        "run-proc": "Het Zapproces:",
        "run-step1": "Demuxing & Update: De tuner splitst het signaal. Keystore-update gebeurt op de achtergrond via de kabel.",
        "run-step2": "OmniView-Boot: Het .oip-pakket wordt geladen, het .hoc-certificaat wordt gevalideerd via de formule of de keystore.",
        "run-step3": "Internetblokkade: Als offline en internet_required is ingesteld op true, stopt het proces met een gestandaardiseerde systeemmelding.",
        "run-step4": "Rendering: Hardware-versnelde overlay met stabiele 60 FPS. De natieve pixel-perfect upscaler activeert voor kanalen ≤ 480p.",
        "run-hw-title": "Off-the-Shelf Hardware-aanbeveling",
        "run-hw-desc": "Vu+ Ultimo 4K: De premium keuze vanwege de enorme FBC-tunerarchitectuur en de optie om een analoge RF-tuner achteraf in te bouwen. Levert meer dan genoeg GPU-kracht voor upscaling, complexe Chromium-apps en realtime malware-reviews."
    }
};

document.getElementById('langSwitch').addEventListener('change', (e) => {
    switchLanguage(e.target.value);
});

function switchLanguage(lang) {
    document.documentElement.lang = lang;
    const elements = document.querySelectorAll('[data-i18n]');
    
    elements.forEach(elem => {
        const key = elem.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            elem.textContent = translations[lang][key];
        }
    });
}
