const translations = {
    de: {
        "hero-title": "DVB-C+ & Holo+ OS: Gesamtspezifikation",
        "hero-desc": "Das Betriebssystem Holo+ bildet die native Schnittstellenplattform für das hybride Kabelsystem DVB-C+. Es regelt die hardwarebeschleunigte Dekodierung hochbitratiger Medienströme, die Ausführung von sendereigenen interaktiven Overlays (OmniView) sowie globalen Systemapplikationen (Apps). Das System trennt zwischen isolierten Broadcast-Erweiterungen und tief integrierten Systemdiensten über ein proprietäres, mehrstufiges Sicherheits- und Zertifikatsmodell.",
        "contrib-title": "Werde Teil der TV-Revolution!",
        "contrib-desc": "DVB-C+ und Holo+ OS sind Open-Source-Projekte, die von der Community leben. Egal ob du Kernel-Entwickler bist, dich mit Tuner-Architekturen auskennst, App-Blueprints schreibst oder die Dokumentation verbessern willst – jede Hilfe bringt uns dem modernen, trackerfreien Kabelfernsehen näher.",
        "contrib-btn": "Jetzt auf GitHub mitwirken",
        "charta-title": "1. Die Holo+ Werbe- & Performance-Charta",
        "charta-tv-allow": "Erlaubt (Klassische TV-Werbung):",
        "charta-tv-allow-desc": "Traditionelle Werbeblöcke im linearen Videostream der Sender sind vollumfänglich erlaubt. Der Receiver greift nicht in das gesendete Bild- und Tonmaterial ein.",
        "charta-app-allow": "Erlaubt (Moderate App- & OmniView-Werbung):",
        "charta-app-allow-desc": "Innerhalb globaler Apps (.hap) und dem OmniView-Interface (.oip) ist Werbung (z. B. Banner, Empfehlungen, In-Content-Promotions) in moderaten Mengen gestattet, um die Entwickler und Sender zu finanzieren. Das visuelle Design darf den Nutzer jedoch nicht in der Kern-Bedienung blockieren oder Menüstrukturen unbrauchbar machen.",
        "charta-forbidden": "Strengstens verboten (Tracker & Werbe-Spam):",
        "charta-forbidden-desc": "Jegliche Form von unsichtbaren Trackern zur Datensammlung, Telemetrie-Schnüfflern, User-Behavior-Analyse oder aufdringlichem Werbe-Spam (z. B. unschließbare Pop-ups) ist auf Protokollebene verboten. Verstößt ein Entwickler oder Sender gegen diese Charta, wird das Zertifikat (.hoc / .hac) über die hardwarebasierte Revocation-List dauerhaft entzogen.",
        "charta-no-ai": "Kein AI-Slop:",
        "charta-no-ai-desc": "Holo+ verzichtet vollständig auf künstlich aufgeblasene Marketing-Features („AI-Optimierung“, „Smart-Predictive-Zapping“ etc.). Alle Bild- und Tonprozesse basieren auf mathematisch präzisen, deterministischen Algorithmen und direkter Hardware-Power, um maximale Stabilität und minimale System-Latenzzeiten zu garantieren.",
        "hw-title": "2. Hardware- & Tuner-Architektur & Retro-Upscaler",
        "hw-single": "Single-Tuner-Geräte:",
        "hw-single-desc": "Exklusiv für den DVB-C+ Standard (4K/8K via AV1/HEVC, Dolby Atmos/FLAC, OmniView).",
        "hw-dual": "Dual-Tuner-Geräte (Retail-Standard):",
        "hw-dual-desc": "Bieten volle Abwärtskompatibilität für klassisches DVB-C (über Tuner 2) und analoge RF-Signale (VHF/UHF).",
        "hw-scaler": "Der Native Retro-Upscaler:",
        "hw-scaler-desc": "Für analoge Signale und digitale Streams mit einer Auflösung von 480p und weniger (z. B. VHS-Videorekorder, Röhren-Konsolen) besitzt Holo+ einen dedizierten, hardwarebeschleunigten Upscaler.",
        "hw-scaler-func": "Funktionsweise:",
        "hw-scaler-func-desc": "Nutzt einen präzisen Integer-Scaling-Algorithmus (Pixel-Perfect-Modus) kombiniert mit einer optionalen, zuschaltbaren Scanline-Simulation, um Unschärfe-Artefakte moderner Panels zu eliminieren.",
        "hw-scaler-req": "Hardware-Voraussetzung:",
        "hw-scaler-req-desc": "Dieses Feature wird nur auf Receivern mit ausreichender GPU-Rechenleistung freigeschaltet.",
        "sec-title": "3. In-Stream Keystore-Update & Offline-Sicherheit",
        "sec-carousel": "Globales Keystore-Karussell:",
        "sec-carousel-desc": "Jeder DVB-C+ Transponder strahlt auf einer geschützten System-PID kontinuierlich den aktuellen, von NeoAudio signierten Master-Keystore aus. Der Receiver aktualisiert seine Sicherheitsdatenbank vollautomatisch und zu 100 % offline über das physische Kabelnetz.",
        "sec-checksum": "Mathematische Prüfziffer (Fallback):",
        "sec-checksum-desc": "Offizielle Zertifikate enthalten eine integrierte Prüfziffer. Die mathematische Formel im OS Holo+ kann diese bei echten Zertifikaten immer erfolgreich auflösen, wodurch das Interface sofort als verifiziert gilt.",
        "sec-window": "30-Tage-Vertrauensfenster:",
        "sec-window-desc": "Schlägt die Formel fehl und das Zertifikat ist unbekannt, läuft die Software für 30 Tage als Kulanz. Der Nutzer wird über diskrete System-Pop-ups gebeten, das Gerät kurzzeitig online zu synchronisieren. Nach 30 Tagen ohne Abgleich erfolgt die Herabstufung in den eingeschränkten Development-Modus.",
        "cert-title": "4. Sicherheits- & Zertifikats-Struktur",
        "cert-desc": "Zertifikate sind UTF-8-kodierte Textdateien, die das OS in numerische Werte auflöst:",
        "cert-hoc": "256 Zeichen. Für sendergebundene .oip-Interfaces.",
        "cert-hac": "256 Zeichen. Für globale Apps (.hap).",
        "cert-hsc": "512 Zeichen. Zwingend erforderlich für System-Services mit tiefen Rechten.",
        "cert-code-title": "Syntax-Aufbau einer Zertifikatsdatei",
        "cert-marker": "Parser-Mechanik:",
        "cert-marker-desc": "Das invertierte Ausrufezeichen ¡ dient dem OS-Kernel als absoluter Startpunkt für das Einlesen der Sicherheitsblöcke. Das standardmäßige ! fungiert als Endpunkt. Alle Zeilen, die mit # beginnen, werden als Kommentar ignoriert.",
        "cert-dev-title": "Der Development-Modus (Unsigniert)",
        "cert-dev-desc": "Software ohne gültiges Zertifikat läuft in einer Sandbox ohne Systemzugriff, zeigt vor dem Start eine Warnung und trägt ein permanentes, transparentes Branding-Badge („Development OmniView Interface“ bzw. „Development Holo+ App“).",
        "oip-title": "5. Das OmniView-Interface (.oip)",
        "oip-rest-title": "Sicherheits-Restriktion:",
        "oip-rest-desc": "Das OmniView-Interface ist ein reines, flüchtiges Anzeige- und Steuerungselement. Im Gegensatz zu globalen Apps ist es einem .oip-Paket auf Systemebene strengstens verboten, eigene Apps, Erweiterungen oder Systemdienste mitzuführen oder nachzuinstallieren. Es darf keinerlei dep-apps-Unterordner besitzen.",
        "oip-schema": "Interface-Namensschema:",
        "oip-blueprint": "Blueprint: Struktur eines OmniView-Interfaces (.oip)",
        
        /* OIP Tree i18n */
        "bp-oip-manifest": "<- Das Interface-Manifest",
        "bp-oip-cert": "<- Das von NeoAudio verifizierte 256-Zeichen-Zertifikat",
        "bp-oip-start": "<- Der definierte Startpunkt für das TV-Overlay",
        "bp-oip-deps": "<- Ordner für skriptbasierte Code-Abhängigkeiten (z.B. UI-Bibliotheken, CSS)",
        "bp-oip-assets": "<- Lokale Grafiken, Kanallogos, Overlays, WebFonts",

        "hap-title": "6. Globale Apps & Kernel-API Struktur (.hap)",
        "hap-schema": "Paket-Namensschema:",
        "hap-desc": "Um Systemsicherheit und schlanke Pakete zu vereinen, unterscheidet Holo+ strikt zwischen drei Abhängigkeitstypen:",
        "api-type1": "Shared System Frameworks: Globale, im OS integrierte Web-Frameworks (react, enact, hls.js).",
        "api-type2": "System Core APIs (holo-app-core): Restriktive System-Schnittstellen. Nur freigeschaltet, wenn das Zertifikat die entsprechenden Berechtigungen besitzt. Ermöglicht Lese- und Schreibzugriff auf sensible Hardware-Ressourcen wie den Tuner-Status, Signalstärken oder den WLAN-Chipsatz.",
        "api-type3": "Selbstgeladene Dependencies (Custom Dependencies): Lokale Bibliotheken des Entwicklers, die im Paket mitgeliefert und über den relativen Pfad deps/ angesprochen werden.",
        "hap-blueprint": "Blueprint: Struktur einer Holo+ App (.hap)",
        
        /* HAP Tree i18n */
        "bp-hap-manifest": "<- Das App-Manifest",
        "bp-hap-cert": "<- Das 256-Zeichen App-Zertifikat",
        "bp-hap-syscert": "<- (NUR bei type \"system\") Das 512-Zeichen System-Zertifikat",
        "bp-hap-start": "<- Der definierte Startpunkt im Chromium-Core",
        "bp-hap-deps": "<- Ordner für AUSSCHLIESSLICH selbstgeladene, proprietäre Code-Abhängigkeiten",
        "bp-hap-depfile": "<- Beispiel für eine selbstgeladene Entwickler-Dependency",
        "bp-hap-depapps": "<- Ordner für zwingend erforderliche Dependency-Apps / System-Services",
        "bp-hap-assets": "<- Lokale Grafiken, Fonts, Audio-Assets",

        "mal-title": "8. Der Malware-Review- & System-Service-Installationsprozess",
        "mal-step1": "Paket-Isolierung:",
        "mal-step1-desc": "Das OS scannt die appinfo.json. Bei Erkennung von \"system\" oder restriktiven Berechtigungsanforderungen innerhalb des holo-app-core (wie z. B. Modifikationen am Tuner oder Netzwerk-Stops) wird der automatische Installationsprozess eingefroren.",
        "mal-step2": "Das Malware-Review-Popup:",
        "mal-step2-desc": "Ein unumgehbares, systemweites Sicherheits-Popup öffnet sich. Dieses Fenster führt eine automatisierte statische Code-Analyse des Dienstes durch und präsentiert dem Nutzer eine klare Zusammenfassung, Erklärung und Risikobewertung.",
        "mal-step3": "Explizite Nutzerbestätigung:",
        "mal-step3-desc": "Die Installation wird erst fortgesetzt, wenn der Nutzer die Risiken aktiv bestätigt und die Installation des System-Services explizit autorisiert.",
        "feat-title": "9. Next-Gen Features von DVB-C+",
        "feat-zap": "Instant-Zap (Pre-Caching):",
        "feat-zap-desc": "Bei Geräten mit FBC-Tunern decodiert Holo+ die I-Frames der umliegenden Kanäle permanent im Hintergrund mit. Das Umschalten erfolgt in unter 0,1 Sekunden.",
        "feat-audio": "Clean-Dialogue-Audio-Mischer:",
        "feat-audio-desc": "Sender können eine separate PID für reine Dialoge mitschicken. Der Nutzer kann im Audiomenü die Stimmen stufenlos anheben – rein über Hardware-Mischung der Tonspuren.",
        "run-title": "10. System-Laufzeitverhalten & Hardware",
        "run-proc": "Der Umschalt-Prozess:",
        "run-step1": "Demuxing & Update: Der Tuner splittet das Signal. Im Hintergrund wird der Keystore über das Kabel aktualisiert.",
        "run-step2": "OmniView-Boot: Das .oip-Paket wird geladen, das .hoc-Zertifikat über die Formel oder den Keystore validiert.",
        "run-step3": "Internet-Sperre: Ist internet_required auf true und der Receiver offline, bricht der Ladevorgang ab und Holo+ gibt eine standardisierte Fehlermeldung aus.",
        "run-step4": "Rendering: Die hardwarebeschleunigte Web-Engine legt das Interface mit stabilen 60 FPS über das TV-Bild. Bei Kanälen von 480p und weniger schaltet sich der native Pixel-Perfect-Upscaler dazu.",
        "run-hw-title": "Off-the-Shelf Hardware-Empfehlung",
        "run-hw-desc": "Vu+ Ultimo 4K: Die Premium-Wahl wegen der massiven FBC-Tuner-Architektur und der Option, einen analogen RF-Zusatztuner für Retro-Geräte nachzurüsten. Liefert mehr als genug GPU-Power für den Upscaler, komplexe Chromium-Apps sowie für das Berechnen der Malware-Reviews bei System-Services."
    },
    en: {
        "hero-title": "DVB-C+ & Holo+ OS: Full Specification",
        "hero-desc": "The Holo+ operating system forms the native interface platform for the hybrid cable system DVB-C+. It governs the hardware-accelerated decoding of high-bitrate media streams, the execution of station-owned interactive overlays (OmniView), and global system applications (Apps). The system separates isolated broadcast extensions from deeply integrated system services via a proprietary, multi-tiered security and certificate model.",
        "contrib-title": "Join the TV Revolution!",
        "contrib-desc": "DVB-C+ and Holo+ OS are open-source projects that thrive on community contributions. Whether you are a kernel developer, familiar with tuner architecture, writing app blueprints, or fixing documentation – every hand brings us closer to modern, tracker-free cable TV.",
        "contrib-btn": "Contribute on GitHub Now",
        "charta-title": "1. The Holo+ Advertising & Performance Charta",
        "charta-tv-allow": "Allowed (Classic TV Ads):",
        "charta-tv-allow-desc": "Traditional ad breaks within the linear video stream of the stations are fully allowed. The receiver does not manipulate the video or audio streams.",
        "charta-app-allow": "Allowed (Moderate App & OmniView Ads):",
        "charta-app-allow-desc": "Within global apps (.hap) and the OmniView interface (.oip), moderate advertising (e.g., banners, recommendations, in-content promotions) is permitted to fund developers and broadcasters. The visual design must not block core system interactions or break navigation layouts.",
        "charta-forbidden": "Strictly Prohibited (Trackers & Spam):",
        "charta-forbidden-desc": "Any type of invisible background trackers, telemetry collection, behavior snooping, or aggressive ad spam (like unclosable pop-ups) is prohibited at protocol level. Violation yields absolute and permanent certificate revocation via hardware-based blacklists.",
        "charta-no-ai": "No AI Slop:",
        "charta-no-ai-desc": "Holo+ completely rejects bloated marketing concepts ('AI scaling', 'Smart Zapping' etc.). Every rendering or mixing pipeline runs via strict deterministic code and raw hardware computing to enforce low latencies.",
        "hw-title": "2. Hardware & Tuner Architecture & Retro Upscaler",
        "hw-single": "Single-Tuner Devices:",
        "hw-single-desc": "Exclusively engineered for the DVB-C+ platform (4K/8K AV1/HEVC, Dolby Atmos/FLAC, OmniView overlays).",
        "hw-dual": "Dual-Tuner Devices (Retail Standard):",
        "hw-dual-desc": "Features full legacy compatibility for classic DVB-C digital cable (via Tuner 2) and analog RF bands (VHF/UHF).",
        "hw-scaler": "The Native Retro Upscaler:",
        "hw-scaler-desc": "For analog inputs or legacy digital video feeds at or below 480p resolution (e.g., VHS decks, vintage gaming hardware).",
        "hw-scaler-func": "Operation:",
        "hw-scaler-func-desc": "Deploys a sharp hardware integer-scaling filter (Pixel-Perfect matrix) combined with customizable CRT scanline emulation to counter panel blur.",
        "hw-scaler-req": "Hardware Dependency:",
        "hw-scaler-req-desc": "This system feature is only unlocked on certified endpoints hosting proper GPU hardware.",
        "sec-title": "3. In-Stream Keystore Carousel & Offline Integrity",
        "sec-carousel": "Transponder Key Carousel:",
        "sec-carousel-desc": "Every DVB-C+ transponder actively pushes the latest NeoAudio master keystore cycle inside an encrypted systems-PID. Updates cascade fully automated and 100% offline via physical coax architecture.",
        "sec-checksum": "Mathematical Validation Fallback:",
        "sec-checksum-desc": "Legitimate code packages contain specialized checksum tags. The built-in mathematical engine inside Holo+ OS evaluates validation strings locally without delay.",
        "sec-window": "30-Day Grace Period:",
        "sec-window-desc": "If local mathematical proofing fails and keys are unknown, an interface is granted 30 days of limited runtime. The UI will request online checks via system alerts before dropping into sandboxed DevMode.",
        "cert-title": "4. Security & Certificate Layers",
        "cert-desc": "Certificates are simple UTF-8 text files resolved locally into raw cryptographic states:",
        "cert-hoc": "256 chars. For station-locked .oip interactive overlays.",
        "cert-hac": "256 chars. For global dashboard applications (.hap).",
        "cert-hsc": "512 chars. Enforced requirement for low-level system automation daemons.",
        "cert-code-title": "Syntax Architecture of a Certificate File",
        "cert-marker": "Parser Logic:",
        "cert-marker-desc": "The inverted exclamation point ¡ marks the exact starting point for parsing system files. The standard ! token registers the closure marker. Lines starting with # are stripped as developer notes.",
        "cert-dev-title": "Development Sandbox (Unsigned Code)",
        "cert-dev-desc": "Any package missing a valid code signature runs in an isolated sandbox, triggers a startup warning and forces a persistent, translucent watermark ('Development OmniView Interface' / 'Development Holo+ App').",
        "oip-title": "5. The OmniView Interface Architecture (.oip)",
        "oip-rest-title": "System Restrictions:",
        "oip-rest-desc": "The OmniView layout layer is an ephemeral display element. Unlike standalone application tiers, it is strictly forbidden for an .oip container to carry, install, or download standalone applications, extensions, or system services. A dep-apps directory is explicitly rejected.",
        "oip-schema": "Container Naming Logic:",
        "oip-blueprint": "Blueprint: OmniView Bundle Tree (.oip)",
        
        /* OIP Tree i18n */
        "bp-oip-manifest": "<- Interface manifest descriptor",
        "bp-oip-cert": "<- NeoAudio approved 256-char layout signature",
        "bp-oip-start": "<- Main interface layout hook for the overlay engine",
        "bp-oip-deps": "<- Library dependencies and styling hooks (e.g., framework variants, layout sheets)",
        "bp-oip-assets": "<- Channel iconography, media layers, static resources, font definitions",

        "hap-title": "6. Global Application Layer & Kernel API (.hap)",
        "hap-schema": "Bundle Naming Logic:",
        "hap-desc": "To ensure maximum protection while keeping bundle sizes small, Holo+ identifies three core dependency tiers:",
        "api-type1": "Shared System Frameworks: Standardized web frameworks pre-baked into the OS kernel (react, enact, hls.js).",
        "api-type2": "System Core APIs (holo-app-core): Locked system hooks. Only reachable if individual certificates permit hardware interactions like network manipulation or live tuner reporting.",
        "api-type3": "Custom Local Dependencies: Unique developer extensions bundled within the container, called via relative paths like deps/.",
        "hap-blueprint": "Blueprint: Holo+ Standalone Application Bundle (.hap)",
        
        /* HAP Tree i18n */
        "bp-hap-manifest": "<- Application manifest descriptor",
        "bp-hap-cert": "<- 256-char core application signature",
        "bp-hap-syscert": "<- (System types ONLY) Low-level 512-char automation signature",
        "bp-hap-start": "<- Main entry node rendered within the sandboxed Chromium container",
        "bp-hap-deps": "<- Reserved EXCLUSIVELY for local, vendor-packaged script extensions",
        "bp-hap-depfile": "<- Sample instance of an embedded application script component",
        "bp-hap-depapps": "<- Required helper binaries, system extensions or background daemons",
        "bp-hap-assets": "<- Static assets, custom fonts, localized audio tracks",

        "mal-title": "8. Security Audits & Low-Level Privilege Authorization",
        "mal-step1": "Container Isolation:",
        "mal-step1-desc": "The OS runs a mandatory check on appinfo.json. If it demands low-level system modes or sensitive holo-app-core configurations (such as tuner locks or active routing filters), automated installation yields immediately.",
        "mal-step2": "The Malware Review Dashboard:",
        "mal-step2-desc": "An unbypassable, high-priority alert system block takes over the UI. It runs an automated static code scan, surfacing an unedited audit log, vulnerability warnings, and structural threat matrix analytics directly to the viewer.",
        "mal-step3": "Explicit Administrative Consent:",
        "mal-step3-desc": "Installation will remain suspended until the human operator actively acknowledges the risk variables and signs off on the deployment of system services manually.",
        "feat-title": "9. Next-Gen Specs within DVB-C+",
        "feat-zap": "Instant-Zap Channel Caching:",
        "feat-zap-desc": "Using FBC-enabled tuner boards, Holo+ permanently mirrors and decodes incoming keyframes (I-Frames) of adjacent channels. Zapping actions take less than 0.1 seconds.",
        "feat-audio": "Isolated Vocal Feed Matrix:",
        "feat-audio-desc": "Broadcasters can multiplex clean dialogue layers on isolated stream parameters. Users can step dialogue parameters up or down natively inside basic system parameters via direct hardware routing.",
        "run-title": "10. Runtime Engine Flow & Targeted Target Architecture",
        "run-proc": "The Channel Zap Sequence:",
        "run-step1": "Demuxing & Update: The tuner demuxes streaming parameters. Keystore karousels update system files silently in the background.",
        "run-step2": "OmniView Boot: The .oip context is mounted while the core signature is authenticated via formula or local key state.",
        "run-step3": "Network Verification: If internet_required evaluates to true and the system is isolated, runtime execution fails, dropping to a native system block interface.",
        "run-step4": "Overlay Rendering: The hardware-accelerated web compositor matches UI frames with the underlying hardware stream at a locked 60 FPS output. Pixel-Perfect scaling blocks step in for feeds matching legacy resolutions ≤ 480p.",
        "run-hw-title": "Off-the-Shelf Reference Implementations",
        "run-hw-desc": "Vu+ Ultimo 4K: The absolute baseline for development. Provides full multi-channel FBC tuner routing options and simple expansion parameters for retro RF blocks. Supplies extensive GPU metrics for software sandboxes, heavy Chromium layers, and real-time malware analysis engines."
    },
    nl: {
        "hero-title": "DVB-C+ & Holo+ OS: Volledige Specificatie",
        "hero-desc": "Het Holo+ besturingssysteem vormt het natieve interfacesplatform voor het hybride kabelsysteem DVB-C+. Het regelt de hardware-versnelde decodering van mediastromen met hoge bitrates, de uitvoering van zendereigen interactieve overlays (OmniView) en globale systeemapplicaties (Apps). Het systeem scheidt geïsoleerde broadcast-extensies van diep geïntegreerde systeemdiensten via een eigen, gelaagd beveiligings- en certificaatmodel.",
        "contrib-title": "Bouw mee aan de tv-revolutie!",
        "contrib-desc": "DVB-C+ en Holo+ OS zijn open-source projecten die floreren dankzij bijdragen van de community. Of je nu een kernel-ontwikkelaar bent, verstand hebt van tunerarchitecturen, app-blueprints schrijft of documentatie wilt oppoetsen – alle hulp brengt ons dichter bij tracker-vrije, moderne kabeltelevisie.",
        "contrib-btn": "Werk nu mee op GitHub",
        "charta-title": "1. Het Holo+ Reclame- & Prestatiehandvest",
        "charta-tv-allow": "Toegestaan (Klassieke TV-reclame):",
        "charta-tv-allow-desc": "Traditionele reclameblokken in de lineaire videostream van de zenders zijn volledig toegestaan. De ontvanger grijpt niet in op het uitgezonden beeld- en geluidsmateriaal.",
        "charta-app-allow": "Toegestaan (Matige App- & OmniView-reclame):",
        "charta-app-allow-desc": "Binnen globale apps (.hap) en de OmniView-interface (.oip) is reclame (bijv. banners, aanbevelingen) in matige hoeveelheden toegestaan om ontwikkelaars en zenders te financieren. Het visuele ontwerp mag de gebruiker niet blokkeren in de kernbediening.",
        "charta-forbidden": "Strikt verboden (Trackers & Advertentiespam):",
        "charta-forbidden-desc": "Elke vorm van onzichtbare trackers voor gegevensverzameling, telemetriesnuffelaars of opdringerige advertentiespam is verboden op protocolniveau. Overtreding leidt tot permanente intrekking van het certificaat (.hoc / .hac) via de hardwarematige intrekkinglijst.",
        "charta-no-ai": "Geen AI-Slop:",
        "charta-no-ai-desc": "Holo+ ziet volledig af van opgeklopte marketingfuncties. Alle beeld- en geluidsprocessen zijn gebaseerd op wiskundig nauwkeurige, deterministische algoritmen en directe hardwarekracht.",
        "hw-title": "2. Hardware- & Tunerarchitectuur & Retro-Upscaler",
        "hw-single": "Single-Tuner-apparaten:",
        "hw-single-desc": "Exclusief voor de DVB-C+ standaard (4K/8K via AV1/HEVC, Dolby Atmos/FLAC, OmniView).",
        "hw-dual": "Dual-Tuner-apparaten (Winkelstandaard):",
        "hw-dual-desc": "Bieden volledige achterwaartse compatibiliteit voor klassieke DVB-C (via Tuner 2) en analoge RF-signalen (VHF/UHF).",
        "hw-scaler": "De Natieve Retro-Upscaler:",
        "hw-scaler-desc": "Voor analoge signalen und digitale streams met een resolutie van 480p en minder (bijv. VHS-videorecorders, beeldbuisconsoles).",
        "hw-scaler-func": "Werking:",
        "hw-scaler-func-desc": "Maakt gebruik van een nauwkeurig integer-scaling-algoritme (pixel-perfect modus) gecombineerd met een optionele scanlijnsimulatie om beeldfouten tegen te gaan.",
        "hw-scaler-req": "Hardwarevereiste:",
        "hw-scaler-req-desc": "Deze functie wordt alleen ontgrendeld op ontvangers met voldoende GPU-rekenkracht.",
        "sec-title": "3. In-Stream Keystore-Update & Offline Beveiliging",
        "sec-carousel": "Globaal Keystore-Carrousel:",
        "sec-carousel-desc": "Elke DVB-C+ transponder zendt continu de nieuwste door NeoAudio ondertekende master-keystore uit. De ontvanger werkt zijn database volledig offline bij via het kabelnetwerk.",
        "sec-checksum": "Wiskundig controlegetal (Fallback):",
        "sec-checksum-desc": "Officiële certificaten bevatten een geïntegreerd controlegetal. De wiskundige formule in Holo+ OS kan dit bij echte certificaten altijd succesvol controleren.",
        "sec-window": "30-Dagen Vertrouwensvenster:",
        "sec-window-desc": "Als de formule faalt, werkt de software 30 dagen als coulanceperiode voordat deze wordt gedowngraded naar de beperkte Ontwikkelmodus.",
        "cert-title": "4. Beveiligings- & Certificaatstructuur",
        "cert-desc": "Certificaten zijn UTF-8 gecodeerde tekstbestanden die het OS omzet in numerieke waarden:",
        "cert-hoc": "256 tekens. Voor zendergebonden .oip-interfaces.",
        "cert-hac": "256 tekens. Voor globale apps (.hap).",
        "cert-hsc": "512 tekens. Verplicht voor systeemdiensten met diepe rechten.",
        "cert-code-title": "Syntaxstructuur van een Certificaatbestand",
        "cert-marker": "Parser-mechanisme:",
        "cert-marker-desc": "Het omgekeerde uitroepteken ¡ dient als het absolute startpunt voor de OS-kernel om de beveiligingsblokken in te lezen. Het standaard ! fungeert als eindpunt. Alle regels die beginnen met # worden als commentaar genegeerd.",
        "cert-dev-title": "De Ontwikkelmodus (Niet ondertekend)",
        "cert-dev-desc": "Software zonder geldig certificaat draait in een sandbox zonder systeemtoegang en is voorzien van een permanente, transparante branding-badge.",
        "oip-title": "5. De OmniView-Interface (.oip)",
        "oip-rest-title": "Beveiligingsrestrictie:",
        "oip-rest-desc": "De OmniView-interface is een puur vluchtig weergave- en bedieningselement. Het is ten strengste verboden om eigen apps of systeemdiensten mee te leveren. Het mag geen dep-apps-submap bevatten.",
        "oip-schema": "Interface-naamschema:",
        "oip-blueprint": "Blueprint: Structuur van een OmniView-interface (.oip)",
        
        /* OIP Tree i18n NL */
        "bp-oip-manifest": "<- Het Interface-Manifest",
        "bp-oip-cert": "<- Het door NeoAudio geverifieerde 256-tekens-certificaat",
        "bp-oip-start": "<- Het gedefinieerde startpunt voor de TV-overlay",
        "bp-oip-deps": "<- Map voor script-gebaseerde afhankelijkheden (bijv. UI-bibliotheken, CSS)",
        "bp-oip-assets": "<- Lokale afbeeldingen, zenderlogo's, overlays, weblettertypen",

        "hap-title": "6. Globale Apps & Kernel-API Structuur (.hap)",
        "hap-schema": "Pakket-naamschema:",
        "hap-desc": "Om systeembeveiliging en slanke pakketten te combineren, maakt Holo+ strikt onderscheid tussen drie typen afhankelijkheden:",
        "api-type1": "Shared System Frameworks: Globale webframeworks geïntegreerd in het OS (react, enact, hls.js).",
        "api-type2": "System Core APIs (holo-app-core): Beperkende systeeminterfaces. Geeft lees- en schrijftoegang tot gevoelige hardwarebronnen zoals de tunerstatus of wifi-chipset.",
        "api-type3": "Custom Local Dependencies: Lokale ontwikkelaarsbibliotheken die in het pakket worden meegeleverd onder het deps/ pad.",
        "hap-blueprint": "Blueprint: Structuur van een Holo+ App (.hap)",
        
        /* HAP Tree i18n NL */
        "bp-hap-manifest": "<- Het App-Manifest",
        "bp-hap-cert": "<- Het 256-tekens App-Certificaat",
        "bp-hap-syscert": "<- (ALLEEN bij type \"system\") Het 512-tekens Systeem-Certificaat",
        "bp-hap-start": "<- Het gedefinieerde startpunt in de Chromium-core",
        "bp-hap-deps": "<- Map voor EXCLUSIEF zelfgeladen, propriëtaire code-afhankelijkheden",
        "bp-hap-depfile": "<- Voorbeeld van een zelfgeladen ontwikkelaars-dependency",
        "bp-hap-depapps": "<- Map voor verplichte dependency-apps / systeemdiensten",
        "bp-hap-assets": "<- Lokale afbeeldingen, lettertypen, audio-assets",

        "mal-title": "8. Het Malware-Review- & Systeemservice-installatieproces",
        "mal-step1": "Pakketisolatie:",
        "mal-step1-desc": "Het OS scant appinfo.json. Bij detectie van 'system' of beperkende core-rechtenaanvragen wordt het automatische installatieproces bevroren.",
        "mal-step2": "De Malware-Review-Popup:",
        "mal-step2-desc": "Er opent een onvermijdelijke systeembrede beveiligingspopup. Dit venster voert een automatische statische codeanalyse uit en toont een samenvatting, uitleg en risicobeoordeling.",
        "mal-step3": "Explicit Gebruikersbevestiging:",
        "mal-step3-desc": "De installatie wordt pas voortgezet nadat de gebruiker de risico's actief bevestigt en de installatie van de systeemservice expliciet autoriseert.",
        "feat-title": "9. Next-Gen Functies van DVB-C+",
        "feat-zap": "Instant-Zap (Pre-Caching):",
        "feat-zap-desc": "Bij apparaten met FBC-tuners decodeert Holo+ de I-frames van omliggende kanalen continu op de achtergrond. Zappen duurt minder dan 0,1 seconden.",
        "feat-audio": "Clean-Dialogue-Audiomixer:",
        "feat-audio-desc": "Zenders kunnen een aparte PID voor pure dialogen meesturen. De gebruiker kan stemmen traploos versterken via pure hardwarematige mixen van de geluidssporen.",
        "run-title": "10. Systeemlooptijdgedrag & Hardware",
        "run-proc": "Het Zapproces:",
        "run-step1": "Demuxing & Update: De tuner splitst het signaal. Keystore-update gebeurt op de achtergrond via de kabel.",
        "run-step2": "OmniView-Boot: Het .oip-pakket wordt geladen, het .hoc-Zertifikat wordt gevalideerd via de formule of de keystore.",
        "run-step3": "Internetblokkade: Als offline en internet_required is ingesteld op true, stopt het proces met een gestandaardiseerde systeemmelding.",
        "run-step4": "Rendering: Hardware-versnelde overlay met stabiele 60 FPS. De natieve pixel-perfect upscaler activeert voor kanalen ≤ 480p.",
        "run-hw-title": "Off-the-Shelf Hardware-aanbeveling",
        "run-hw-desc": "Vu+ Ultimo 4K: De premium keuze vanwege de enorme FBC-tunerarchitectuur en de optie om een analoge RF-tuner achteraf in te bouwen. Levert meer dan genoeg GPU-kracht voor upscaling, complexe Chromium-apps en realtime malware-reviews."
    }
};

document.getElementById('langSwitch').addEventListener('change', (e) => {
    switchLanguage(e.target.value);
});

function switchLanguage(lang) {
    document.documentElement.lang = lang;
    const elements = document.querySelectorAll('[data-i18n]');
    
    elements.forEach(elem => {
        const key = elem.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            // Check if element has explicit child icons we need to preserve
            const iconSpan = elem.querySelector('.material-symbols-outlined');
            if (iconSpan) {
                const textNode = Array.from(elem.childNodes).find(node => node.nodeType === Node.TEXT_NODE);
                if (textNode) {
                    textNode.textContent = " " + translations[lang][key];
                } else {
                    elem.innerHTML = iconSpan.outerHTML + " " + translations[lang][key];
                }
            } else {
                elem.textContent = translations[lang][key];
            }
        }
    });
}
